### ISSUE TITLE
Access to the pretrained model for the QDMR parser

### ISSUE THREAD

**Issue by nooralahzadeh** [tomerwolgithub/question-decomposition-to-sql#1]
Hi,

Thanks for sharing the code!
I wonder whether is possible to access the pretrained model for the QDMR parser which is based on T5-large?

Thanks

**Comment by tomerwolgithub** [comment]
Hello,

The checkpoint of our trained QDMR parser has been added to the README. The model can also be downloaded from [here](https://storage.googleapis.com/ai2i/qdmr_parser_t5/QDMR_parser_T5_large.zip).
